language: node_js
node_js:
  - '8'

cache:
  directories: 
    - 'node_modules'

branches:
  only:
    - main

install:
  - npm install
  - npm run generate
  
script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local_dir: dist
  on:
    branch: main
